audit+measure-1: Fix expected number of entries for ima-ng template
Fix the following test case error when ima-ng is used:

Error: Wrong number of ' cause=open_writers .*rootfs/testfile' entries in audit log.
       Expected 1, found 2.

The test cases now works with ima-sig and ima-ng with or without
a rule like "audit func=BPRM_CHECK mask=MAY_EXEC" installed on the
host. This rule does influence the number of messages emitted for
open_writes and ToMToU.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>